*Titanic*

*¿Quién sobrevivió?*

*Propósito*

El objetivo de este conjunto de datos es predecir quién podría haber
sobrevivido al desastre del Titanic. Aunque ciertamente hubo un elemento
de suerte en la supervivencia, parece que algunos grupos de personas
tenían más probabilidades de sobrevivir que otros.

*Fuente*

Este conjunto de datos se encontró originalmente en Kaggle.

*Contenido*

Te ayudo a describir todas las columnas del dataset del Titanic que mencionas primero. Aquí está la descripción completa:

1. **PassengerId**: Número de identificación único asignado a cada pasajero
2. **Survived**: Indica si el pasajero sobrevivió
   - 0 = No sobrevivió
   - 1 = Sobrevivió
3. **Pclass**: Clase del ticket (clase socioeconómica)
   - 1 = Primera clase
   - 2 = Segunda clase
   - 3 = Tercera clase
4. **Name**: Nombre completo del pasajero
5. **Sex**: Sexo del pasajero
   - male = masculino
   - female = femenino
6. **Age**: Edad del pasajero (en años)
7. **SibSp**: Número de hermanos/cónyuges a bordo
   - Sib = hermanos, hermanas, hermanastros, hermanastras
   - Sp = cónyuge (esposo o esposa)
8. **Parch**: Número de padres/hijos a bordo
   - Par = padre o madre
   - Ch = hijos
9. **Ticket**: Número del ticket
10. **Fare**: Tarifa pagada por el pasaje
11. **Cabin**: Número de cabina
12. **Embarked**: Puerto de embarque
   - C = Cherbourg
   - Q = Queenstown
   - S = Southampton

Esta versión tiene algunas columnas adicionales (PassengerId, Ticket, Cabin, Embarked) comparada con la segunda versión, pero mantiene las variables más importantes para el análisis de supervivencia.

*Descarga*

Puedes descargar el conjunto de datos desde la línea de comandos:

#+begin_src sh
wget https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
#+end_src

--------------

